In [1]:
import torch

In [67]:
import numpy as np

In [17]:
x = torch.empty(3,3, dtype=int)

In [27]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [28]:
x

tensor([[0.6842, 0.2788],
        [0.3200, 0.3794]])

In [29]:
y

tensor([[0.8319, 0.9038],
        [0.9007, 0.0016]])

In [30]:
x + y

tensor([[1.5161, 1.1826],
        [1.2207, 0.3809]])

In [31]:
x

tensor([[0.6842, 0.2788],
        [0.3200, 0.3794]])

underscores "_" refers to inplace operation

In [32]:
x.add_(y)

tensor([[1.5161, 1.1826],
        [1.2207, 0.3809]])

In [33]:
x

tensor([[1.5161, 1.1826],
        [1.2207, 0.3809]])

### Elementwise Operations

In [38]:
x = torch.rand(2,2)
y = torch.rand(2,2)

In [39]:
x

tensor([[0.4274, 0.3124],
        [0.0995, 0.9278]])

In [40]:
y

tensor([[0.6522, 0.7023],
        [0.3625, 0.3846]])

In [41]:
torch.add(x,y)

tensor([[1.0796, 1.0147],
        [0.4620, 1.3124]])

In [42]:
torch.sub(x,y)

tensor([[-0.2248, -0.3899],
        [-0.2630,  0.5431]])

In [43]:
torch.mul(x,y)

tensor([[0.2788, 0.2194],
        [0.0361, 0.3568]])

In [44]:
torch.div(x,y)

tensor([[0.6554, 0.4448],
        [0.2744, 2.4122]])

### Indexing

In [47]:
x = torch.rand(5,4,3)

In [48]:
x

tensor([[[0.8071, 0.8538, 0.0141],
         [0.4259, 0.9659, 0.1629],
         [0.2645, 0.4679, 0.1196],
         [0.8310, 0.2010, 0.9629]],

        [[0.6560, 0.9673, 0.3029],
         [0.6849, 0.5877, 0.3613],
         [0.8584, 0.0116, 0.9308],
         [0.1588, 0.1796, 0.0041]],

        [[0.9610, 0.3153, 0.8468],
         [0.6196, 0.5293, 0.8838],
         [0.3099, 0.4402, 0.9073],
         [0.4323, 0.9119, 0.8777]],

        [[0.1370, 0.1210, 0.2619],
         [0.9902, 0.0738, 0.2706],
         [0.0050, 0.6665, 0.3645],
         [0.0596, 0.4060, 0.8573]],

        [[0.0887, 0.2522, 0.4678],
         [0.6175, 0.6414, 0.7719],
         [0.5347, 0.3289, 0.9395],
         [0.4666, 0.3637, 0.9970]]])

In [54]:
x[0]

tensor([[0.8071, 0.8538, 0.0141],
        [0.4259, 0.9659, 0.1629],
        [0.2645, 0.4679, 0.1196],
        [0.8310, 0.2010, 0.9629]])

In [52]:
x[:,0]

tensor([[0.8071, 0.8538, 0.0141],
        [0.6560, 0.9673, 0.3029],
        [0.9610, 0.3153, 0.8468],
        [0.1370, 0.1210, 0.2619],
        [0.0887, 0.2522, 0.4678]])

In [53]:
x[:,:,0]

tensor([[0.8071, 0.4259, 0.2645, 0.8310],
        [0.6560, 0.6849, 0.8584, 0.1588],
        [0.9610, 0.6196, 0.3099, 0.4323],
        [0.1370, 0.9902, 0.0050, 0.0596],
        [0.0887, 0.6175, 0.5347, 0.4666]])

### Reshape tensors

In [55]:
x = torch.rand(4,4)

In [56]:
x

tensor([[0.2498, 0.1761, 0.2081, 0.2488],
        [0.3900, 0.3638, 0.2667, 0.7420],
        [0.9190, 0.1749, 0.5448, 0.3520],
        [0.8886, 0.2302, 0.1095, 0.0859]])

In [58]:
x.view(2,8)

tensor([[0.2498, 0.1761, 0.2081, 0.2488, 0.3900, 0.3638, 0.2667, 0.7420],
        [0.9190, 0.1749, 0.5448, 0.3520, 0.8886, 0.2302, 0.1095, 0.0859]])

if not sure about the size put -1 as first size and second size element as required

In [61]:
x.view(-1,8)

tensor([[0.2498, 0.1761, 0.2081, 0.2488, 0.3900, 0.3638, 0.2667, 0.7420],
        [0.9190, 0.1749, 0.5448, 0.3520, 0.8886, 0.2302, 0.1095, 0.0859]])

### Type conversion

Torch to Numpy

In [62]:
x = torch.rand(3,4)

In [65]:
y = x.numpy()

In [64]:
type(x)

torch.Tensor

In [66]:
type(y)

numpy.ndarray

Numpy to Torch

In [71]:
x = np.ones((6,4))

In [72]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [73]:
y = torch.from_numpy(x)

In [74]:
y

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [75]:
type(x)

numpy.ndarray

In [76]:
type(y)

torch.Tensor

Note: When GPU acceleration is available, conversion between numpy and cuda/mps(for mac) require