In [48]:
import torch

In [49]:
x = torch.rand(3,requires_grad = True)

In [50]:
x

tensor([0.6463, 0.2027, 0.0987], requires_grad=True)

In [51]:
y = x + 2

In [52]:
y

tensor([2.6463, 2.2027, 2.0987], grad_fn=<AddBackward0>)

Create a 'add_backward' function which calculate gradients for backpropagation

In [53]:
z = y*y*2

In [54]:
z = z.mean()

In [55]:
z

tensor(10.8396, grad_fn=<MeanBackward0>)

forward propagation with multiplication creates a MulBackward function and mean will create MeanBackward

backward function will calculate output gradient with respect to input

In [56]:
z.backward() # dz/dx

In [57]:
z

tensor(10.8396, grad_fn=<MeanBackward0>)

In [58]:
x.grad

tensor([3.5285, 2.9369, 2.7983])

Sometimes we do not want to calculate gradients in the intermediate steps and want to prevent tracking history in computational grpah
So this can be be done in 3 ways

    1) x.requires_grad_(False)
    2) x.detach()
    2) with torch.no_grad():
    

In [62]:
x

tensor([0.6463, 0.2027, 0.0987], requires_grad=True)

In [30]:
x.requires_grad_(False)

tensor([0.3453, 0.6740, 0.7629])

In [31]:
x.detach()

tensor([0.3453, 0.6740, 0.7629])

In [45]:
with torch.no_grad():
    y = x + 2

Note: It is important to empty graidents at the end of every iteration to prevent accumuation

In [63]:
x.grad.zero_()

tensor([0., 0., 0.])